import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.scss";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/util/Providers";

import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

const locales = ["ru", "en"];

export const metadata: Metadata = {
  title: "Wetravel - travel around Uzbekistan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!locales.includes(locale as any)) notFound();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
